### PR TITLE
Add to list after save

### PR DESCRIPTION
**Pull request by laurieboyes**
After saving, suggest adding content to an existing list

Overlay presentation is not ready for production and is behind `myftLists` flag

### CODE REVIEW

**Comment by matthew-andrews** [comment]
React?

**Comment by Lrnk** [comment]
@matthew-andrews Ha, interesting suggestion. Just for the sake of trying React on some other stuff or because you think it would bring other benefits (e.g. performance)?

**Comment by matthew-andrews** [comment]
would be good to evaluate it across the team…  and also some accessibilty benefits? (not blasting the dom away every time?)

**Comment by Lrnk** [comment]
abandoning this in favour of a solution that requires no client-side templating or whatever at all

**Comment by Lrnk** [comment]
Overlay populated from fragment served by next-myft-page instead of using client-side templating
Content ID parameter is sanitised by next-myft-page
Behaviour is still behind the myftLists flag

**Comment by keirog** [comment]
:+1:

**Pull request merged**
